name: dfs-analysis
channels:
  - conda-forge
dependencies:
  - requests
  - python=3.11
  - pandas
  - streamlit>=1.50
  - plotly
  - scikit-learn
  - numpy
  - scipy
  - pip
  - pip:
    - pandas-stubs
    - types-requests
